server:
  port: 8888
spring:
  application:
    name: mybatis-plugins-demo
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:mysql://localhost:3306/test
    username: root

mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: pepelu.demo.plugins.mybatis.model
  configuration:
    map-underscore-to-camel-case: true
  plugins:
    enum-package: pepelu.demo.plugins.mybatis.model
